### ISSUE TITLE
System.ArgumentException: Rule must have at least one match action

### ISSUE THREAD

**Issue by mwolf** [NRules/NRules#205]
Hi There

I was trying to create a dynamic RuleSet based on rules configured in our database.
Some of them are used multiple times within one single ruleset.
I was following the solution mentioned in the following issue:
https://github.com/NRules/NRules/issues/65

Nevertheless I always receive the following exception when trying to build the rules:

```
NRules.Fluent.RuleDefinitionException: Failed to build rule definition
SlaughterCheckService.Rules.Definitions.ParameterRule01.ParameterRule01Error, SlaughterCheckService.Rules, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 ---> System.ArgumentException: Rule must have at least one match action
   at NRules.RuleModel.Builders.Element.ActionGroup(IEnumerable`1 actions)
   at NRules.RuleModel.Builders.ActionGroupBuilder.NRules.RuleModel.Builders.IBuilder<NRules.RuleModel.ActionGroupElement>.Build()
   at NRules.RuleModel.Builders.RuleBuilder.Build()
   at NRules.Fluent.Dsl.Rule.BuildDefinition()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at NRules.Fluent.Dsl.Rule.GetDefinition()
   at NRules.Fluent.RuleDefinitionFactory.Create(Rule rule)
   --- End of inner exception stack trace ---
   at NRules.Fluent.RuleDefinitionFactory.Create(Rule rule)
   at NRules.Fluent.RuleDefinitionFactory.Create(IEnumerable`1 rules)
   at NRules.Fluent.RuleLoadSpec.Load()
   at NRules.Fluent.RuleRepository.Load(Action`1 specAction)
```

My rule is really basic (see on below):

```
public class ParameterRule01Error : Rule
{
		private readonly Parameter01 _parameter;
		public ParameterRule01Error(Parameter01 parameter)
		{
			_parameter = parameter;
		}

		public override void Define()
		{
			Cow cow = null;

			When()
				.Match<Cow>(() => cow, c => c.BirthDate.HasValue);
			Then()
				.Solve(null, cow, "ParameterRule01Error Message", _parameter);
		}
}
```

My rules activator:

```
public class RulesActivator : IRuleActivator
	{
		private readonly ILifetimeScope _scope;

		public RulesActivator(ILifetimeScope scope)
		{
			_scope = scope;
		}

		public IEnumerable<Rule> Activate(Type type)
		{
			yield return (Rule)_scope.Resolve(type);
		}
	}
```

I'm activating my rules like this:

```
var builder = new ContainerBuilder();
builder.Register(x => new ParameterRule01Error(param)).AsSelf();
var container = builder.Build();
var repository = new RuleRepository();
repository.Activator = new RulesActivator(container);
repository.Load(x => x.From(Assembly.Load("SlaughterCheckService.Rules")));
var ruleSets = repository.GetRuleSets();
var compiler = new RuleCompiler();
var factory = compiler.Compile(ruleSets);

//Create a working session
var session = factory.CreateSession();
```

Now it fails when trying to load the rules with the mentioned exception.
I have no idea whats going wrong since the match expression is defined and I did everything as described in the documentation.

Before I moved to the AutoFac RulesActivator (due to the requirement to have a rule more than once) my rule worked perfectly.

Do you have any idea what's going wrong here?

Thanks in advance
Magnus

**Comment by mwolf** [comment]
Ok, forget about it. After a lot of debugging, I just recognized that it was a null reference in a dependency which was used by my DSLExtensions. 
Unfortunately the error message was a bit misleading.
So this issue is solved. Sorry for that.

**Comment by snikolayev** [comment]
Thanks for circling back and reporting that the issue is resolved.
