### ISSUE TITLE
OR Operator causing "Duplicate Declaration" exception - bug

### ISSUE THREAD

**Issue by Miller-Kyle** [NRules/NRules#220]
Seems like this is either due to me not fully understanding how to use the OR operator, or it is a bug.

```
NRules.Fluent.RuleDefinitionException
  HResult=0x80131500
  Message=Failed to build rule definition
Scratch.OrRuleTest, Scratch, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  Source=NRules.Fluent
  StackTrace:
   at NRules.Fluent.RuleDefinitionFactory.Create(Rule rule)
   at NRules.Fluent.RuleDefinitionFactory.Create(IEnumerable`1 rules)
   at NRules.Fluent.RuleLoadSpec.Load()
   at NRules.Fluent.RuleRepository.Load(Action`1 specAction)
   at Scratch.Program.Main(String[] args) in 

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
InvalidOperationException: Duplicate declarations. Declaration=$var1$,$var2$
```

Here is a sample to reproduce the issue:

```
namespace Scratch
{
    using System;
    using System.Linq;
    using System.Reflection;

    using NRules;
    using NRules.Fluent;
    using NRules.Fluent.Dsl;

    internal class Program
    {
        private static void Main(string[] args)
        {
            var repository = new RuleRepository();
            repository.Load(x => x.From(Assembly.GetExecutingAssembly()));
            var sessionFactory = repository.Compile();
            var session = sessionFactory.CreateSession();

            session.Insert(new Fact1());
            session.Insert(new Fact2());
            session.Insert(new Fact3());
            session.Insert(new Fact4());

            session.Fire();

            var output = session.Query<string>().Single();
            Console.WriteLine(output);
            Console.ReadLine();
        }
    }

    public class OrRuleTest : Rule
    {
        public override void Define()
        {
            this.When()
                .Match<Fact1>()
                .Match<Fact2>()
                .Or(x => 
                    x.Match<Fact3>()
                    .Match<Fact4>());
            this.Then().Do(context => context.Insert("Test"));
        }
    }

    public class Fact1
    {
    }

    public class Fact2
    {
    }

    public class Fact3
    {
    }

    public class Fact4
    {
    }
}
```

I dug a bit into the ElementValidator class where the exception is being thrown and I can see that the export names are the same as the export names outside of the OR group. This is what I found:

Var1 is used for Fact1 and Fact3
Var2 is used for Fact2 and Fact4

![image](https://user-images.githubusercontent.com/62899600/77939575-65a8ce80-7285-11ea-91d5-1c55695af3e9.png)

If this is due to me using the OR group wrong can you please instruct me on how to use it correctly?

**Workaround**
If you declare variables for the facts, even if you don't plan to use them outside the match, the exception goes away.
```
public class OrRuleTest : Rule
    {
        public override void Define()
        {
            Fact1 fact1WorkAround = null;
            Fact2 fact2WorkAround = null;
            this.When()
                .Match<Fact1>(() => fact1WorkAround)
                .Match<Fact2>(() => fact2WorkAround)
                .Or(x => 
                    x.Match<Fact3>()
                    .Match<Fact4>());
            this.Then().Do(context => context.Insert("Test"));
        }
    }
```

**Comment by snikolayev** [comment]
I can confirm, it's a bug with Match statements that don't use aliases. The bug is with the logic that creates default variable names for the matches.
As a temporary workaround, as you indicated, you can just use Match statements that explicitly bind to an alias:
```c#
        public class OrRuleTest : Rule
        {
            public override void Define()
            {
                Fact1 fact1 = null;
                Fact2 fact2 = null;
                Fact3 fact3 = null;
                Fact4 fact4 = null;

                When()
                    .Match<Fact1>(() => fact1)
                    .Match<Fact2>(() => fact2)
                    .Or(x => x
                        .Match<Fact3>(() => fact3)
                        .Match<Fact4>(() => fact4));

                Then()
                    .Do(context => context.Insert("Test"));
            }
        }
```

**Comment by Miller-Kyle** [comment]
Thank you @snikolayev. I will use the workaround!.
