### ISSUE TITLE
Better Exception Reporting

### ISSUE THREAD

**Issue by drusellers** [NRules/NRules#59]
I recently got an exception that says "Group condition AND requires at least one child element" but looking at the exception I have no idea what rule is causing this. :(

I looked at https://github.com/NRules/NRules/blob/develop/src/NRules/NRules.RuleModel/Builders/GroupBuilder.cs#L135 and I can't see any _obvious_ places to enrich this with more data.

Any thoughts?

Stack trace:

```
   at NRules.RuleModel.Builders.GroupBuilder.Validate() in c:\GitHub\NRules\src\NRules\NRules.RuleModel\Builders\GroupBuilder.cs: line 139
   at NRules.RuleModel.Builders.GroupBuilder.NRules.RuleModel.Builders.IBuilder<NRules.RuleModel.GroupElement>.Build() in c:\GitHub\NRules\src\NRules\NRules.RuleModel\Builders\GroupBuilder.cs: line 107
   at NRules.RuleModel.Builders.RuleBuilder.Build() in c:\GitHub\NRules\src\NRules\NRules.RuleModel\Builders\RuleBuilder.cs: line 105
   at NRules.Fluent.Dsl.Rule.BuildDefinition() in c:\GitHub\NRules\src\NRules\NRules.Fluent\Dsl\Rule.cs: line 85
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at NRules.Fluent.Dsl.Rule.GetDefinition() in c:\GitHub\NRules\src\NRules\NRules.Fluent\Dsl\Rule.cs: line 73
   at NRules.Fluent.RuleRepository.<Load>b__1(Rule r) in c:\GitHub\NRules\src\NRules\NRules.Fluent\RuleRepository.cs: line 51
   at System.Linq.Enumerable.<>c__DisplayClass12`3.<CombineSelectors>b__11(TSource x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at NRules.RuleModel.RuleSet.Add(IEnumerable`1 ruleDefinitions) in c:\GitHub\NRules\src\NRules\NRules.RuleModel\IRuleSet.cs: line 44
   at NRules.Fluent.RuleRepository.Load(Action`1 specAction) in c:\GitHub\NRules\src\NRules\NRules.Fluent\RuleRepository.cs: line 57
   at MRG.Fulfillment.Features.InventoryCommitment.AssignInventoryPolicy..ctor() in AssignInventoryPolicy.cs: line 15
   at Fulfillment.UnitTests.TryTheRulesOut.AssigningInventoryWithRules() in TryTheRulesOut.cs: line 39
```

**Comment by snikolayev** [comment]
Hi Dru,
Can you please post the rule that fails to compile? 

The 'And' group is an element that groups rule patterns using the AND logical operator. It requires child elements,  and throws this exception if there are none.  That's why I'm asking for the rule code. 
'And' group is also the root element in every rule, so a rule without any conditions will throw this exception.

**Comment by snikolayev** [comment]
Oh, I see, you don't know which rule fails to compile. My guess is that you have a rule without conditions that's causing this. 
I'll improve error handling in this area.

**Comment by drusellers** [comment]
I found it. I had a completely empty rule.

I couldn't find one with an AND so that made it tricky. :)

-d

On Thu, Apr 16, 2015 at 12:18 PM, Sergiy Nikolayev <notifications@github.com

**Comment by snikolayev** [comment]
Great. I'll definitely improve error handling in this area though, thanks for reporting. When it fails DSL validation, it doesn't even get to compilation, so it doesn't get covered by error handling and diagnostics implemented at that level. Good catch

**Comment by drusellers** [comment]
Absolutely, i'm hoping to use your project on my next project. So hopefully I can start sending in some PRs as well for little things like this.

**Comment by snikolayev** [comment]
I won't get to my laptop before Monday,  so if you decide to take a stab at this one, it will involve changes in NRules.Fluent. 
I would wrap the call to Rule.GetDefinition and raise a new custom exception (i.e. RuleDefinitionException or something like that), and include rule type and original exception.

**Comment by drusellers** [comment]
whoo hoo :)
